# Generated by Django 5.2.17 on 2026-10-03 01:53

import apps.orders.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0003_stockmovement_product_storage_instructions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(default=apps.orders.models.order_reference, editable=False, max_length=24, unique=True)),
                ('idempotency_key', models.UUIDField(editable=False, unique=True)),
                ('request_fingerprint', models.CharField(editable=False, max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('delivery', models.CharField(choices=[('retiro_local', 'Retiro local'), ('entrega_local', 'Reparto local')], max_length=20)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('address_help', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('A_CONFIRMAR', 'A confirmar'), ('RESERVADO', 'Reservado'), ('PREPARANDO', 'Preparando'), ('LISTO_PARA_RETIRO', 'Listo para retirar'), ('EN_REPARTO', 'En reparto'), ('TERMINADO', 'Terminado'), ('CANCELADO', 'Cancelado'), ('VENCIDO', 'Vencido')], default='A_CONFIRMAR', max_length=24)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('internal_note', models.TextField(blank=True)),
                ('reserved_at', models.DateTimeField(blank=True, null=True)),
                ('reservation_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.customer')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=24)),
                ('to_status', models.CharField(choices=[('A_CONFIRMAR', 'A confirmar'), ('RESERVADO', 'Reservado'), ('PREPARANDO', 'Preparando'), ('LISTO_PARA_RETIRO', 'Listo para retirar'), ('EN_REPARTO', 'En reparto'), ('TERMINADO', 'Terminado'), ('CANCELADO', 'Cancelado'), ('VENCIDO', 'Vencido')], max_length=24)),
                ('public_note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id_snapshot', models.PositiveBigIntegerField()),
                ('product_name', models.CharField(max_length=160)),
                ('sku', models.CharField(max_length=64)),
                ('weight_grams', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.order')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='order_nonnegative_subtotal'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.UniqueConstraint(fields=('order', 'variant'), name='order_unique_variant'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='order_positive_quantity'),
        ),
    ]
